-- Histopathology booking schema for Supabase.
-- Apply this file in the Supabase SQL editor, then enable Anonymous Sign-Ins
-- under Authentication > Providers. The browser must only use the publishable key.

create extension if not exists pgcrypto;

create sequence if not exists public.booking_number_seq start with 1000;

create table if not exists public.instruments (
  id text primary key,
  name text not null,
  tagline text not null,
  icon text not null,
  sop text not null,
  sort_order integer not null unique
);

create table if not exists public.specimen_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null unique
);

create table if not exists public.sop_documents (
  id bigint generated by default as identity primary key,
  title text not null,
  file text not null unique,
  sop_no text not null unique,
  sort_order integer not null unique
);

create table if not exists public.facility_contacts (
  id bigint generated by default as identity primary key,
  role text not null,
  name text not null,
  phone text not null,
  email text not null,
  sort_order integer not null unique
);

create table if not exists public.facility_settings (
  key text primary key,
  value jsonb not null
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  booking_id text not null unique default ('HP-' || lpad(nextval('public.booking_number_seq')::text, 4, '0')),
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  user_name text not null,
  pi_name text not null,
  phone text not null,
  email text not null,
  institution text not null default '',
  specimen_type text not null references public.specimen_types(name),
  instrument_id text not null references public.instruments(id),
  date date not null,
  slot text not null check (slot in ('09:00 - 11:00', '11:00 - 13:00', '14:00 - 16:00', '16:00 - 18:00')),
  form_filename text not null,
  status text not null default 'booked' check (status in ('booked', 'completed', 'cancelled')),
  created_at timestamptz not null default now(),
  unique (instrument_id, date, slot)
);

create index if not exists bookings_created_by_idx on public.bookings(created_by);
create index if not exists bookings_week_idx on public.bookings(date, instrument_id, slot);

insert into public.instruments (id, name, tagline, icon, sop, sort_order) values
  ('leica-tissue-processor', 'Leica Tissue Processor', 'Automated tissue processing', 'processor', 'sop-tissue-processing-unit.pdf', 1),
  ('leica-embedding', 'Leica Tissue Embedding Station', 'Paraffin embedding', 'embedding', 'sop-tissue-embedding-station.pdf', 2),
  ('leica-microtome', 'Leica Microtome', 'Rotary microtome', 'microtome', 'sop-microtome.pdf', 3),
  ('medimeas-microtome', 'Medimeas Microtome', 'Rotary microtome', 'microtome', 'sop-microtome.pdf', 4),
  ('medimeas-cryostat', 'Medimeas Cryostat', 'Cryosectioning', 'cryostat', 'sop-cryostat.pdf', 5),
  ('leica-vibratome', 'Leica Vibratome', 'Vibratome sectioning', 'vibratome', 'sop-vibratome.pdf', 6),
  ('zeiss-slide-scanner', 'Zeiss Slide Scanner', 'Digital slide scanning', 'scanner', 'sop-slide-scanner.pdf', 7),
  ('vision-embedding', 'Vision Embedding Station', 'Embedding station', 'embedding', 'sop-tissue-embedding-station.pdf', 8),
  ('vision-processing', 'Vision Tissue Processing Unit', 'Tissue processing', 'processor', 'sop-tissue-processing-unit.pdf', 9),
  ('vision-stainer', 'Vision Slide Stainer', 'Automated slide staining', 'stainer', 'sop-slide-stainer.pdf', 10)
on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, icon = excluded.icon, sop = excluded.sop, sort_order = excluded.sort_order;

insert into public.specimen_types (name, sort_order) values
  ('Formalin-fixed paraffin-embedded (FFPE)', 1),
  ('Fresh-frozen tissue', 2),
  ('Resin-embedded block', 3),
  ('Cell pellet / smear', 4),
  ('Other (specify in notes)', 5)
on conflict (name) do update set sort_order = excluded.sort_order;

insert into public.sop_documents (title, file, sop_no, sort_order) values
  ('Tissue Processing Unit', 'sop-tissue-processing-unit.pdf', 'LAB-HISTO-01', 1),
  ('Tissue Embedding Station', 'sop-tissue-embedding-station.pdf', 'LAB-HISTO-02', 2),
  ('Microtome', 'sop-microtome.pdf', 'LAB-HISTO-03', 3),
  ('Cryostat', 'sop-cryostat.pdf', 'LAB-HISTO-04', 4),
  ('Vibratome', 'sop-vibratome.pdf', 'LAB-HISTO-05', 5),
  ('Slide Scanner', 'sop-slide-scanner.pdf', 'LAB-HISTO-06', 6),
  ('Slide Stainer', 'sop-slide-stainer.pdf', 'LAB-HISTO-07', 7)
on conflict (file) do update set title = excluded.title, sop_no = excluded.sop_no, sort_order = excluded.sort_order;

insert into public.facility_contacts (role, name, phone, email, sort_order) values
  ('TA Incharge', 'Keerthana H S', '7975911869', 'keerthana@iisc.ac.in', 1),
  ('Faculty Incharge', 'Prof. Srimonta Gayen', '08022933677', 'srimonta@iisc.ac.in', 2)
on conflict (sort_order) do update set role = excluded.role, name = excluded.name, phone = excluded.phone, email = excluded.email;

insert into public.facility_settings (key, value) values
  ('user_form', '{"title":"Facility User Form","file":"user-form.pdf"}'::jsonb)
on conflict (key) do update set value = excluded.value;

-- The booking window is Friday noon through Sunday 11:59 AM (Asia/Kolkata).
-- It always applies to the following Monday-Sunday booking week.
create or replace function public.current_booking_week_start(at_time timestamptz default now())
returns date
language sql
stable
as $$
  select (date_trunc('week', timezone('Asia/Kolkata', at_time)::date::timestamp)::date + 7);
$$;

create or replace function public.booking_window_open(at_time timestamptz default now())
returns boolean
language plpgsql
stable
as $$
declare
  local_time timestamp := timezone('Asia/Kolkata', at_time);
  day_number integer := extract(isodow from local_time);
begin
  return (day_number = 5 and local_time::time >= time '12:00')
      or day_number = 6
      or (day_number = 7 and local_time::time < time '12:00');
end;
$$;

create or replace function public.get_booking_context()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  week_start date := public.current_booking_week_start();
  is_open boolean := public.booking_window_open();
begin
  return jsonb_build_object(
    'week_days', (
      select jsonb_agg(to_char(day_value::date, 'YYYY-MM-DD') order by day_value)
      from generate_series(week_start, week_start + 6, interval '1 day') as days(day_value)
    ),
    'open', is_open,
    'message', case when is_open
      then 'Booking window is open — book any available slot until Sunday 11:59 AM.'
        else 'Booking window is closed. Opens Friday 12:00 PM, closes Sunday 11:59 AM, for the upcoming week.'
    end
  );
end;
$$;

create or replace function public.booking_session_starts_at(booking_date date, booking_slot text)
returns timestamptz
language sql
immutable
as $$
  select (booking_date + split_part(booking_slot, ' - ', 1)::time) at time zone 'Asia/Kolkata';
$$;

create or replace function public.validate_booking_window()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if not public.booking_window_open() then
    raise exception 'Bookings are only accepted Friday 12:00 PM through Sunday 11:59 AM (Asia/Kolkata).';
  end if;
  if new.date < public.current_booking_week_start()
     or new.date > public.current_booking_week_start() + 6 then
    raise exception 'The booking date must be in the upcoming booking week.';
  end if;
  if new.created_by is distinct from auth.uid() then
    raise exception 'A booking must belong to the authenticated anonymous user.';
  end if;
  return new;
end;
$$;

drop trigger if exists bookings_validate_window on public.bookings;
create trigger bookings_validate_window
before insert or update on public.bookings
for each row execute function public.validate_booking_window();

create or replace function public.get_booking_availability(p_instrument_id text, p_week_start date)
returns table(date date, slot text, status text)
language sql
stable
security definer
set search_path = public
as $$
  with slots(slot) as (
    values ('09:00 - 11:00'), ('11:00 - 13:00'), ('14:00 - 16:00'), ('16:00 - 18:00')
  )
  select days::date, slots.slot,
         case when bookings.id is null then 'available' else 'booked' end
  from generate_series(p_week_start, p_week_start + 6, interval '1 day') as dates(days)
  cross join slots
  left join public.bookings
    on bookings.instrument_id = p_instrument_id
   and bookings.date = days::date
   and bookings.slot = slots.slot
   and bookings.status = 'booked'
  order by days, slots.slot;
$$;

create or replace function public.get_booking_stats(p_week_start date)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'total', count(*) filter (where status = 'booked'),
    'users', count(distinct email) filter (where status = 'booked'),
    'pending', count(*) filter (where status = 'booked'),
    'completed', count(*) filter (where status = 'completed')
  )
  from public.bookings
  where date between p_week_start and p_week_start + 6;
$$;

alter table public.instruments enable row level security;
alter table public.specimen_types enable row level security;
alter table public.sop_documents enable row level security;
alter table public.facility_contacts enable row level security;
alter table public.facility_settings enable row level security;
alter table public.bookings enable row level security;

drop policy if exists instruments_read_authenticated on public.instruments;
create policy instruments_read_authenticated on public.instruments for select to authenticated using (true);
drop policy if exists specimen_types_read_authenticated on public.specimen_types;
create policy specimen_types_read_authenticated on public.specimen_types for select to authenticated using (true);
drop policy if exists sop_documents_read_authenticated on public.sop_documents;
create policy sop_documents_read_authenticated on public.sop_documents for select to authenticated using (true);
drop policy if exists facility_contacts_read_authenticated on public.facility_contacts;
create policy facility_contacts_read_authenticated on public.facility_contacts for select to authenticated using (true);
drop policy if exists facility_settings_read_authenticated on public.facility_settings;
create policy facility_settings_read_authenticated on public.facility_settings for select to authenticated using (true);

drop policy if exists bookings_read_own on public.bookings;
create policy bookings_read_own on public.bookings for select to authenticated
  using (created_by = auth.uid());
drop policy if exists bookings_insert_own on public.bookings;
create policy bookings_insert_own on public.bookings for insert to authenticated
  with check (created_by = auth.uid());
drop policy if exists bookings_update_own on public.bookings;
create policy bookings_update_own on public.bookings for update to authenticated
  using (created_by = auth.uid() and status = 'booked')
  with check (created_by = auth.uid() and status = 'booked');
drop policy if exists bookings_cancel_own_before_session on public.bookings;
create policy bookings_cancel_own_before_session on public.bookings for delete to authenticated
  using (created_by = auth.uid() and status = 'booked'
    and public.booking_session_starts_at(date, slot) > now());

grant select on public.instruments, public.specimen_types, public.sop_documents,
  public.facility_contacts, public.facility_settings to authenticated;
grant select, insert, update, delete on public.bookings to authenticated;
grant usage, select on sequence public.booking_number_seq to authenticated;
revoke execute on function public.get_booking_context() from public;
revoke execute on function public.get_booking_availability(text, date) from public;
revoke execute on function public.get_booking_stats(date) from public;
grant execute on function public.get_booking_context() to authenticated;
grant execute on function public.get_booking_availability(text, date) to authenticated;
grant execute on function public.get_booking_stats(date) to authenticated;

-- Make booking INSERT/UPDATE/DELETE events available to the browser realtime
-- client. RLS still controls which rows a signed-in anonymous user can read.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_rel pr
       join pg_class c on c.oid = pr.prrelid
       join pg_namespace n on n.oid = c.relnamespace
       join pg_publication p on p.oid = pr.prpubid
       where p.pubname = 'supabase_realtime' and n.nspname = 'public' and c.relname = 'bookings'
     ) then
    alter publication supabase_realtime add table public.bookings;
  end if;
end;
$$;
